<a href="https://colab.research.google.com/github/Siddharth-Singh-Verma/tensorflow_notes/blob/main/00_tensorflow_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This notebook will have basics of tensorflow  from my tesnsorflow developer couse

this will cover
* introduction to tensor
* geting info from tensor
* manipulate tensor
* tensors an numpy
* using tf.function
* use gpu and tpu
* exercises to try

## introduction to tensors

In [1]:
# importing tensorflow
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.15.0


In [2]:
# creating tensors using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimension of a tensor
scalar.ndim

0

In [4]:
#create vector
vector=tf.constant([10,10,10])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
#create a matrix
matrix = tf.constant([[10,7],
                     [1,2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix= tf.constant([[10.,2],
                              [20.,10],
                              [2.,3.3]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10. ,  2. ],
       [20. , 10. ],
       [ 2. ,  3.3]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# dimension = no of elements in shape

tensor = tf.constant([[[1,2],
                      [2,3]],
                     [[2,3],
                      [2,3]]] )
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 3]],

       [[2, 3],
        [2, 3]]], dtype=int32)>

In [11]:
tensor.ndim

3

* scalar : a single number
* vector : a number with direction (eg wind speed and direction )
* matrix : a 2 dimentional array of numbers
* tensor : an n-dimensional array of numbers(where n can be any number , 0 dim, 1- dim vector)

# Creating  tensors with tf.Variable(Vis cap)

In [12]:
# creating same tensor as above but with tf.variable

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor= tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# lets change element in changeble tensor
changeable_tensor[0]=7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [14]:
# using .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# doing it on unchangble
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

❗**Note** rarely in pratice will we need to decide whether to use constant or Variable to create tensors ,as tensorflow does  this for us .How ever if in doubt use tf.constant and change it later if needed

# creating random tensors
random tensor are tensor of some abitrary size of random numbers

In [16]:
# creating 2 random tensors but same?

random_1=tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1.shape


TensorShape([3, 2])

In [17]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [18]:
random_2=tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [19]:
random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [20]:
random2=tf.random.normal(shape = (3,2))
random2
# alwayse diffrent so we set seed of first

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.4716239 ,  0.23721464],
       [-0.65602136,  0.33782724],
       [ 1.054406  ,  1.7749828 ]], dtype=float32)>

What if you wanted to shuffle the order of a tensor?

Wait, why would you want to do that?

Let's say you working with 15,000 images of cats and dogs and the first 10,000 images of were of cats and the next 5,000 were of dogs. This order could effect how a neural network learns (it may overfit by learning the order of the data), instead, it might be a good idea to move your data around.

In [21]:

# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [22]:
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

Wait... why didn't the numbers come out the same?

It's due to rule #4 of the tf.random.set_seed() documentation.

"4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

tf.random.set_seed(42) sets the global seed, and the seed parameter in tf.random.shuffle(seed=42) sets the operation seed.

Because, "Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed."

In [23]:

# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [24]:
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

Other ways to make tensors
Though you might rarely use these (remember, many tensor operations are done behind the scenes for you), you can use tf.ones() to create a tensor of all ones and tf.zeros() to create a tensor of all zeros.

In [25]:
tf.zeros(shape=(5,2,3))

<tf.Tensor: shape=(5, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

# turning numpy array into tensors
tensor can be run on gpu so they are faster

In [26]:

# x= tf.constant(some_matrix)#capital for matrix or tensor
# y= tf.constant(vector) non-capital for vectors

In [27]:
numpy_A = np.arange(1,25,dtype=np.int32)
print(numpy_A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [28]:
x=tf.constant(numpy_A)
x

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [29]:
y=tf.constant(numpy_A,shape=(4,6)) # 4*6 = 24 else it will give error
y

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]], dtype=int32)>

# getting information from tensors
some attributes of tensors
* shape
* rank
* axis or dimension
* size

In [31]:
# creating a rank 4 tensors
rank_4_tensors= tf.zeros(shape=[2,3,4,5])
rank_4_tensors

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensors[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [35]:
rank_4_tensors.shape, rank_4_tensors.ndim, tf.size(rank_4_tensors)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [40]:
print("datatype of every element" ,rank_4_tensors.dtype)
print("number of dimension", rank_4_tensors.ndim)
print("shape" ,rank_4_tensors.shape)
print("element along last axis",rank_4_tensors[-1].shape)
print("number of elements ",tf.size(rank_4_tensors))
print("number of elements ",tf.size(rank_4_tensors).numpy())

datatype of every element <dtype: 'float32'>
number of dimension 4
shape (2, 3, 4, 5)
element along last axis (3, 4, 5)
number of elements  tf.Tensor(120, shape=(), dtype=int32)
number of elements  120


### indexing tensor
just like python list

In [44]:
# to get first 2 element of each dimension
rank_4_tensors[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [47]:
rank_4_tensors

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [48]:
# get first element from each dimension from each index except for the final one

rank_4_tensors[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [55]:
rank_4_tensors[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [51]:
r2tensor=tf.constant([[10,20],
                     [30,40]])
r2tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [53]:
# last element
r2tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 40], dtype=int32)>

In [57]:
# adding new dimension
r3tensor = r2tensor[...,tf.newaxis]
r3tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [20]],

       [[30],
        [40]]], dtype=int32)>

## tensor manipulation (elements operation on tensor)
**basic operation**

' + - * / '

In [59]:
tensor=tf.constant([[10,20],[20,10]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 30],
       [30, 20]], dtype=int32)>

In [60]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 10]], dtype=int32)>

In [61]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 200],
       [200, 100]], dtype=int32)>

In [64]:
(tensor[0,0]*10).numpy()

100

In [66]:
# using build in functions of TF
tf.multiply(tensor,10)
# faster than tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 200],
       [200, 100]], dtype=int32)>

In [67]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 10]], dtype=int32)>

In [73]:
# matrices multiplication

print(tensor)
print(tf.matmul(tensor,tensor))

tf.Tensor(
[[10 20]
 [20 10]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[500 400]
 [400 500]], shape=(2, 2), dtype=int32)


In [70]:
tensor * tensor
#diff output as it is elemnt wise not matrice multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 400],
       [400, 100]], dtype=int32)>

In [74]:
tensor @ tensor # using pythor operator

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[500, 400],
       [400, 500]], dtype=int32)>