<a href="https://colab.research.google.com/github/Siddharth-Singh-Verma/tensorflow_notes/blob/main/00_tensorflow_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This notebook will have basics of tensorflow  from my tesnsorflow developer couse

this will cover
* introduction to tensor
* geting info from tensor
* manipulate tensor
* tensors an numpy
* using tf.function
* use gpu and tpu
* exercises to try

## introduction to tensors

In [ ]:
# importing tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# creating tensors using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimension of a tensor
scalar.ndim

0

In [ ]:
#create vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create a matrix
matrix = tf.constant([[10,7],
                     [1,2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix= tf.constant([[10.,2],
                              [20.,10],
                              [2.,3.3]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10. ,  2. ],
       [20. , 10. ],
       [ 2. ,  3.3]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# dimension = no of elements in shape

tensor = tf.constant([[[1,2],
                      [2,3]],
                     [[2,3],
                      [2,3]]] )
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 3]],

       [[2, 3],
        [2, 3]]], dtype=int32)>

In [ ]:
tensor.ndim

3

* scalar : a single number
* vector : a number with direction (eg wind speed and direction )
* matrix : a 2 dimentional array of numbers
* tensor : an n-dimensional array of numbers(where n can be any number , 0 dim, 1- dim vector)

# Creating  tensors with tf.Variable(Vis cap)

In [ ]:
# creating same tensor as above but with tf.variable

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor= tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# lets change element in changeble tensor
changeable_tensor[0]=7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# using .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# doing it on unchangble
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

❗**Note** rarely in pratice will we need to decide whether to use constant or Variable to create tensors ,as tensorflow does  this for us .How ever if in doubt use tf.constant and change it later if needed

# creating random tensors